config/routes.rb
Rails.application.routes.draw do
  root 'places#index'
  resources :places, only: [:index, :show]
  get 'photos/:id/show', to: 'photos#show', as: 'photos_show'

end

app/models/place.rb
class Place
  include ActiveModel::Model

  attr_accessor :id, :formatted_address, :location, :address_components

  def initialize(params={})
    @id= params[:_id].to_s
    @formatted_address = params[:formatted_address]

    if params[:location]
      @location = Point.new(params[:location])
    else
      if params[:geometry] && params[:geometry][:geolocation]
        @location = Point.new(params[:geometry][:geolocation])
      else
        @location = nil
      end

    end

    if params[:address_components]
      @address_components = params[:address_components].map {|h| AddressComponent.new(h)}
    else
      @address_components = []
    end
  end

  def persisted?
    !@id.nil?
  end

  # def id
  #   BSON::ObjectId.from_string(@id)
  # end

  # convenience method for access to client in console
  def self.mongo_client
    Mongoid::Clients.default
  end

  # convenience method for access to zips collection
  def self.collection
    self.mongo_client['places']
  end

  def self.load_all(file)
    contents = file.read
    hash=JSON.parse(contents)
    places=Place.collection
    places.insert_many(hash)
  end

  def self.find_by_short_name(short_name)
    self.collection.find(:address_components => {:$elemMatch => { :short_name=>short_name}})
  end

  def self.to_places(mongo_cursor)
    places = []
    mongo_cursor.each do |doc|
      if doc
        places << Place.new(doc)
      end
    end
    places
  end

  def self.find(id)
    if id
      doc = self.collection.find(:_id=>BSON::ObjectId.from_string(id)).first
      doc ?  Place.new(doc) : nil
    else
      nil
    end
  end

  def self.all(offset=nil, limit=nil)
    mongo_cursor = self.collection.find()
    mongo_cursor=mongo_cursor.skip(offset) unless offset.nil?
    mongo_cursor=mongo_cursor.limit(limit) unless limit.nil?
    self.to_places(mongo_cursor)
  end

  def destroy
    self.class.collection.find({:_id=>BSON::ObjectId.from_string(@id)}).delete_one
  end

  def self.get_address_components(sort=nil, offset=nil, limit=nil)
    query = []
    query << {:$project=>{ :_id=>1, :address_components=>1, :formatted_address=>1, 'geometry.geolocation'=>1}}
    query << {:$unwind=>'$address_components'}
    query << {:$sort=>sort} unless sort.nil?
    query << {:$skip=>offset} unless offset.nil?
    query << {:$limit=>limit} unless limit.nil?
    self.collection.find.aggregate(query)
  end

  def self.get_country_names
    query = []
    query << {:$project=>{ :_id=>1, :address_components=>1}}
    query << {:$unwind=>'$address_components'}
    query << {:$unwind=>'$address_components.types'}
    query << {:$match=>{'address_components.types'=>'country'}}
    query << {:$group=>{:_id=>'$address_components.long_name'}}
    self.collection.find.aggregate(query).to_a.map {|h| h[:_id]}
  end

  def self.find_ids_by_country_code(country_code)
    query = []
    query << {:$project=>{ :_id=>1, :address_components=>1}}
    #query << {:$unwind=>'$address_components'}
    query << {:$match=>{'address_components.short_name'=>country_code}}
    query << {:$project=>{ :_id=>1}}
    self.collection.find.aggregate(query).map {|doc| doc[:_id].to_s}
  end

  def self.create_indexes
    self.collection.indexes.create_one({ 'geometry.geolocation' => Mongo::Index::GEO2DSPHERE })
  end

  def self.remove_indexes
    self.collection.indexes.drop_all
  end

  def self.near(point, max_meters=nil)
    query_hash = {}
    query_hash[:'$geometry'] = point.to_hash
    query_hash[:'$maxDistance'] = max_meters unless max_meters.nil?
    self.collection.find('geometry.geolocation' => {:'$near'=> query_hash})
  end

  def near(max_meters=nil)
    self.class.to_places(self.class.near(self.location, max_meters))
  end

  def photos(offset=0, limit=nil)
    mongo_cursor = Photo.find_photos_for_place(@id)
    mongo_cursor=mongo_cursor.skip(offset) unless offset.nil?
    mongo_cursor=mongo_cursor.limit(limit) unless limit.nil?
    mongo_cursor.to_a.map {|doc| Photo.new(doc)}
  end

  end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:formatted_address)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :formatted_address %><br>
    <%= f.text_field :formatted_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Places</h1>

<table>
  <thead>
    <tr>
      <th>Formatted address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @places.each do |place| %>
      <% photo=place.photos.sample %>
      <tr>
        <td><%= place.formatted_address %></td>
        <% if photo %>
            <td><img height="50px" width="65px" src= <%= photos_show_path("#{photo.id}")%>/></td>
        <% end %>
        <td><%= link_to 'Show', place %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Formatted address:</strong>
  <%= @place.formatted_address %>
</p>
<% @place.photos.each do |photo| %>
    <p>
      <img height="500px" width="650px" src= <%= photos_show_path("#{photo.id}")%>/>
    </p>
<% end %>

<%= link_to 'Back', places_path %>